### ISSUE TITLE
Admin API breaking in macOS Mojave 10.14.4 

### ISSUE THREAD

**Issue by MichelinMan** [Kong/homebrew-kong#99] opened 2019-04-02 12:27 UTC
I had a working configuration of Kong 1.0 running on macOS Mojave 10.14.4
Brew successfully updated Kong to version 1.1 when I did a brew upgrade.
However since then I am not able to get any response from the Admin API.

    curl http://localhost:8001

I find this problem very difficult to debug as the only think I see in the logs are these entries for each request to the Admin API url, nothing else.

    2019/04/02 13:19:20 [notice] 49919#0: signal 20 (SIGCHLD) received from 49929
    2019/04/02 13:19:20 [alert] 49919#0: worker process 49929 exited on signal 11
    2019/04/02 13:19:20 [notice] 49919#0: start worker process 50168
    2019/04/02 13:19:20 [notice] 49919#0: signal 23 (SIGIO) received
    2019/04/02 13:19:20 [notice] 49919#0: signal 23 (SIGIO) received
    2019/04/02 13:19:20 [notice] 49919#0: signal 23 (SIGIO) received from 49920

I have since tried uninstalling kong, luarocks and openresty and installing kong, so that brew will re-install these packages but the results are the same. Likewise I have thrown out the configuration database, and also thrown out the kong.conf file, to have a clean vanilla install, but each time the results are the same.

Perhaps the problem is at the OS level because the entries in the logs are Unix signals thrown from threads.

Also I have a second computer that is running macOS High Sierra and there Kong was also updated to version 1.1 from a brew upgrade command but it all works just fine.

Perhaps the way to reproduce this is to do a brew install kong on a Mac running Mojave?

I would be grateful for any help,
Ioannis

**Comment by tholu** [comment] 2019-04-06 07:27
I'll try to reproduce this.

**Comment by tholu** [comment] 2019-04-06 08:39
I can reproduce this with 1.1.1 as well.

```
2019/04/06 10:36:40 [alert] 49469#0: worker process 49531 exited on signal 11
2019/04/06 10:36:40 [notice] 49469#0: start worker process 49555
2019/04/06 10:36:40 [notice] 49469#0: signal 23 (SIGIO) received
2019/04/06 10:36:40 [notice] 49469#0: signal 23 (SIGIO) received
2019/04/06 10:36:40 [notice] 49469#0: signal 23 (SIGIO) received from 49553
2019/04/06 10:36:40 [notice] 49469#0: signal 23 (SIGIO) received from 49553
2019/04/06 10:36:40 [notice] 49469#0: signal 23 (SIGIO) received
2019/04/06 10:36:40 [notice] 49469#0: signal 23 (SIGIO) received from 49553
```

**Comment by MichelinMan** [comment] 2019-04-08 10:53
Same problem persists in Kong 1.1.1

**Comment by tholu** [comment] 2019-04-08 12:17
See https://github.com/Kong/homebrew-kong/issues/99 for the results of my investigation into the issue so far.

**Comment by hutchic** [comment] 2019-04-09 13:17
I don't own a mac so can't help with homebrew but there is the option of using Docker with a mounted volume to develop Kong https://github.com/Kong/kong-build-tools#developing-kong (related PR: https://github.com/Kong/kong/pull/4491)

**Comment by josephbruni** [comment] 2019-04-10 17:50
Not sure if this is helpful or just redundant. It looks like SIGIO is sent to a process when a file descriptor (socket) becomes writable and I/O is possible. However, the default behavior when receiving this signal is to terminate the process. The idea is that the signal handler should have been set up propertly before enabling async I/O on a socket.

Is this why we are seeing complains about SIGIO in the error.log?

**Comment by dndx** [comment] 2019-04-11 06:52
Hello guys,

we are able to identify the root cause of this problem and here is a temporary fix you can try: https://github.com/Kong/kong/issues/4471#issuecomment-481989146

Let me know if it works!

**Comment by dndx** [comment] 2019-04-12 15:54
Hello guys,

We have provided a long-term fix in https://github.com/Kong/openresty-patches/pull/39 and this issue should be fixed now. You may revert back the changes to `pcre`'s formula and reinstall `kong` with `pcre`, the problem should no longer be persistent!

Appreciate the feedback as well!

**Closed by dndx** 2019-04-12 15:54 UTC
