### ISSUE TITLE
error: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version while accessing https://github.com/kong/homebrew-kong/info/refs?service=git-upload-pack

### ISSUE THREAD

**Issue by dmitriz** [Kong/homebrew-kong#68] opened 2018-04-15 04:34 UTC
Trying this on OSX 10.8 
```sh
$ brew -v
Homebrew 1.6.0
Homebrew/homebrew-core (git revision e04a2; last commit 2018-04-15)
```

```sh
$ brew tap kong/kong
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (caskroom/cask, homebrew/core).
No changes to formulae.

==> Tapping kong/kong
Cloning into '/usr/local/Homebrew/Library/Taps/kong/homebrew-kong'...
error: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version while accessing https://github.com/kong/homebrew-kong/info/refs?service=git-upload-pack
fatal: HTTP request failed
Error: Failure while executing: git clone https://github.com/kong/homebrew-kong /usr/local/Homebrew/Library/Taps/kong/homebrew-kong --depth=1
```

**Comment by deanwang2018** [comment] 2018-05-01 23:46
I met the same issue, I'm using macOS 10.13.4 , how to bypass this issue ? Thanks !

**Comment by ingmaras** [comment] 2021-04-11 12:52
Still an issue in 2021.

**Comment by kikito** [comment] 2021-05-12 17:18
I am not able to reproduce this issue in a more current version of homebrew.

**Comment by kikito** [comment] 2021-05-12 18:00
Closing this for now. Please reopen if more information (with a newer version of homebrew) is available.

**Closed by kikito** 2021-05-12 18:00 UTC
